// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCEf2k-sf93Iy9BiGOXPdhNUEorxWIlzPE',
    appId: '1:380549189293:web:5e4449913c440dd11d0024',
    messagingSenderId: '380549189293',
    projectId: 'dwixy-2ed5c',
    authDomain: 'dwixy-2ed5c.firebaseapp.com',
    storageBucket: 'dwixy-2ed5c.firebasestorage.app',
    measurementId: 'G-S4S0SN3Y8Q',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAIXFHywNLrcymLuza_nlU_yzpU8Rq9ky0',
    appId: '1:380549189293:android:6ecefc0d52ed93831d0024',
    messagingSenderId: '380549189293',
    projectId: 'dwixy-2ed5c',
    storageBucket: 'dwixy-2ed5c.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBaruADmrzut3FihyMw1VaBtLLOzx3oRmM',
    appId: '1:380549189293:ios:5be2dc5f0d47d7b31d0024',
    messagingSenderId: '380549189293',
    projectId: 'dwixy-2ed5c',
    storageBucket: 'dwixy-2ed5c.firebasestorage.app',
    iosBundleId: 'com.example.dwixy',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBaruADmrzut3FihyMw1VaBtLLOzx3oRmM',
    appId: '1:380549189293:ios:5be2dc5f0d47d7b31d0024',
    messagingSenderId: '380549189293',
    projectId: 'dwixy-2ed5c',
    storageBucket: 'dwixy-2ed5c.firebasestorage.app',
    iosBundleId: 'com.example.dwixy',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCEf2k-sf93Iy9BiGOXPdhNUEorxWIlzPE',
    appId: '1:380549189293:web:58d9de8c132c303a1d0024',
    messagingSenderId: '380549189293',
    projectId: 'dwixy-2ed5c',
    authDomain: 'dwixy-2ed5c.firebaseapp.com',
    storageBucket: 'dwixy-2ed5c.firebasestorage.app',
    measurementId: 'G-NDWEFYXWWM',
  );
}